In [79]:
import numpy as np

In [80]:
# Python Init 2D Array Using Numpy
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
# Python Blank Zeros Array Generate
a1 = np.zeros([3,3])
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [82]:
# Python Ganerate 2D Array With Anay Char Or Number
a2 = np.full([3,3],3)
print(a2)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [83]:
# Generate Range Num. Without Gap
a3 = np.arange(10,20)
print(a3)

[10 11 12 13 14 15 16 17 18 19]


In [84]:
# Ganerate Range Num. With Gap (3 Param is Gap)
a4 = np.arange(10,50,5)
print(a4)

[10 15 20 25 30 35 40 45]


In [85]:
# Numpy Random Number Generate
h5 = np.random.randint(100,1000,10)
print(h5)

[809 953 372 945 374 800 691 591 490 434]


In [86]:
# Array Reshape Function
p1 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

p1.shape = (5,2)
print(p1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [87]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

# Array Virtual Stack
p1 = np.vstack([n1,n2]);
print(p1)
print("---------------------------");

# Array Horizontal Stack
p2 = np.hstack([n1,n2])
print(p2)
print("---------------------------");

# Array Column Stack
p3 = np.column_stack([n1,n2])
print(p3)
print("---------------------------");

[[1 2 3]
 [4 5 6]]
---------------------------
[1 2 3 4 5 6]
---------------------------
[[1 4]
 [2 5]
 [3 6]]
---------------------------


In [88]:
# 2 Array Comman Array Value Fun.
n1 = np.array([1,2,3,6])
n2 = np.array([1,2,5,6])
j1 = np.intersect1d(n1,n2)
print(j1)

[1 2 6]


In [89]:
# 2 Array Different Array Value
n1 = np.array([1,3,56,7])
n2 = np.array([1,5,7,4])
p1 = np.setdiff1d(n1,n2)
print(p1)

[ 3 56]


In [90]:
# Array Virticat Sum Fun.
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
p1 = np.sum([n1,n2], axis=0)
print(p1)

[5 7 9]


In [93]:
# Array Horizontal Sum Fun.
n1 = np.array([1,2,3])
n1 = np.array([4,5,6])
p1 = np.sum([n1,n2], axis=1)
print(p1)

[15 15]


In [94]:
# Summ Of Array Total
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
p1 = np.sum([n1,n2])
print(p1)

21


In [98]:
# Basic Addition Array Value Number
n1 = np.array([
    [1,2,3],
    [4,5,6],
])
n1 = n1 + 1
print(n1)

[[3 4 5]
 [6 7 8]]


In [99]:
# Basic Subtraction Array Value Number
n1 = np.array([
    [1,2,3],
    [4,5,6]
])
n1 = n1 - 1
print(n1)

[[0 1 2]
 [3 4 5]]


In [100]:
# Basic Multiplication Array Value Number
n1 = np.array([
    [1,2,3],
    [4,5,6]
])
n1 = n1 * 2
print(n1)

[[ 2  4  6]
 [ 8 10 12]]


In [102]:
# Basic Division Array Value Number
n1 = np.array([
    [10,20,30],
    [40,50,60]
])
n1 = n1 / 2
print(n1)

[[ 5. 10. 15.]
 [20. 25. 30.]]
