In [1]:
import numpy as np

In [2]:
# Python Init 2D Array Using Numpy
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Python Blank Zeros Array Generate
a1 = np.zeros([3,3])
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Python Ganerate 2D Array With Anay Char Or Number
a2 = np.full([3,3],3)
print(a2)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [21]:
# Generate Range Num. Without Gap
a3 = np.arange(10,20)
print(a3)

[10 11 12 13 14 15 16 17 18 19]


In [45]:
# Ganerate Range Num. With Gap (3 Param is Gap)
a4 = np.arange(10,50,5)
print(a4)

[10 15 20 25 30 35 40 45]


In [48]:
# Numpy Random Number Generate
h5 = np.random.randint(100,1000,10)
print(h5)

[163 256 927 331 550 645 542 306 458 922]


In [60]:
# Array Reshape Function
p1 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

p1.shape = (5,2)
print(p1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [66]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
# Array Virtual Stack
p1 = np.vstack([n1,n2]);
print(p1)
print("---------------------------");
# Array Horizontal Stack
p2 = np.hstack([n1,n2])
print(p2)
print("---------------------------");
# Array Column Stack
p3 = np.column_stack([n1,n2])
print(p3)
print("---------------------------");

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
